<?php

defined('BASEPATH') OR exit('No direct script access allowed');
//$config['uri_segment'] = 3;
//$config['num_links'] = 2;
//$config['use_page_numbers'] = TRUE;
//$config['reuse_query_string'] = FALSE;
//$config['prefix'] = '';
//$config['suffix'] = '';
//$config['use_global_url_suffix'] = FALSE;
$config['full_tag_open'] = '<ul class="pagination">';
$config['full_tag_close'] = '</ul>';
//$config['first_link'] = 'First';
//$config['first_tag_open'] = '<div>';
//$config['first_tag_close'] ='</div>';
//$config['first_url'] = '';
//$config['last_tag_open'] = '<div>';
//$config['last_tag_close'] = '</div>';
$config['next_link'] = 'Next';
$config['next_tag_open'] = '<li class="paginate_button next">';
$config['next_tag_close'] =  '</li>';
$config['prev_link'] = 'Previous';
$config['prev_tag_open'] = '<li class="paginate_button previous">';
$config['prev_tag_close'] =  '</li>';
$config['cur_tag_open'] = '<li class="paginate_button active"><a href="#" aria-controls="itoffside.com" data-dt-idx="1" tabindex="0">';
$config['cur_tag_close'] = '</a></li>';
$config['num_tag_open'] = '<li class="paginate_button">';
$config['num_tag_close'] =  '</li>';
//$config['display_pages'] = FALSE;
//$config['attributes']['rel'] = FALSE;
